export interface MockProductInput {
  title: string;
  brand: string;
  price: number;
  rating: number;
  category: string;
  description: string;
  specifications: Record<string, string>;
  reviews: string[];
  features: string[];
  image: string;
}

export const mockProducts: MockProductInput[] = [
  // LAPTOPS
  {
    title: "ASUS TUF Gaming A15",
    brand: "ASUS",
    price: 75990,
    rating: 4.4,
    category: "laptops",
    description: "High-performance gaming laptop with AMD Ryzen 7 7735HS, 16GB DDR5 RAM, 512GB SSD, and NVIDIA GeForce RTX 3050. Features a durable chassis and an exceptionally large 90Wh battery offering up to 8 hours of battery life. Built for heavy gaming, coding, and multitasking under a budget of 80k.",
    specifications: {
      Processor: "AMD Ryzen 7 7735HS (8 Cores/16 Threads)",
      RAM: "16GB DDR5 4800MHz (Upgradable to 32GB)",
      Storage: "512GB PCIe Gen4 NVMe SSD",
      Graphics: "NVIDIA GeForce RTX 3050 4GB GDDR6",
      Display: "15.6-inch FHD (1920 x 1080) IPS, 144Hz Refresh Rate",
      Battery: "90Whr (Up to 8 hours daily usage)",
      Weight: "2.20 kg",
      OS: "Windows 11 Home",
    },
    features: [
      "Military-grade MIL-STD-810H durability",
      "90Whr battery for extended gaming & coding",
      "144Hz smooth refresh rate screen",
      "Dual self-cleaning fan design",
    ],
    reviews: [
      "Excellent value for money. Easily plays GTA V and Cyberpunk on medium settings. Battery life is surprising for a gaming laptop, lasted 7 hours during web browsing.",
      "A bit heavy to carry to college, but the build is solid. The keyboard backlight is nice, and typing is comfy. Strongly recommend for engineering students on a budget.",
      "The screen brightness could be better, colors look slightly washed out. But performance-wise, it's a beast under 80000.",
    ],
    image: "laptop_gaming_asus",
  },
  {
    title: "Apple MacBook Air M3",
    brand: "Apple",
    price: 114900,
    rating: 4.8,
    category: "laptops",
    description: "Supercharged by the M3 chip, this ultra-thin, silent, fanless laptop offers up to 18 hours of battery life. Perfect for software development, writing code, professional editing, and daily office productivity. Slim aluminum design, liquid retina display, and fast unified memory integration.",
    specifications: {
      Processor: "Apple M3 chip (8-core CPU, 8-core GPU)",
      RAM: "8GB Unified Memory",
      Storage: "256GB Superfast SSD",
      Display: "13.6-inch Liquid Retina Display with True Tone (2560 x 1664)",
      Battery: "52.6Whr (Up to 18 hours Apple TV app movie playback)",
      Weight: "1.24 kg",
      OS: "macOS",
    },
    features: [
      "Fanless design for completely silent operation",
      "Stunning 13.6-inch Liquid Retina display with 500 nits brightness",
      "Incredible battery life lasting up to 18 hours",
      "Super slim profile, only 1.13 cm thin",
    ],
    reviews: [
      "I love this machine. Carrying it in my bag is effortless since it weights next to nothing. Battery literally lasts me two full working days of writing code.",
      "M3 chip is blazing fast. Even with 8GB RAM, Docker and VS Code run smoothly. Best developer laptop.",
      "Pricing is high, especially for SSD upgrades, but the build quality and screen are unparalleled.",
    ],
    image: "laptop_apple_air",
  },
  {
    title: "Razer Blade 15 Elite",
    brand: "Razer",
    price: 219990,
    rating: 4.6,
    category: "laptops",
    description: "Premium elite gaming laptop featuring an Intel Core i7-13700H, NVIDIA GeForce RTX 4070, 16GB DDR5, and a 1TB SSD. Housed in a CNC anodized aluminum chassis, with a QHD 240Hz screen. Ultimate laptop for heavy video editing, AAA gaming, and premium creators.",
    specifications: {
      Processor: "Intel Core i7-13700H (14 Cores / 20 Threads)",
      RAM: "16GB DDR5 5200MHz",
      Storage: "1TB PCIe Gen4 NVMe SSD",
      Graphics: "NVIDIA GeForce RTX 4070 8GB GDDR6",
      Display: "15.6-inch QHD (2560 x 1440), 240Hz, 100% DCI-P3",
      Battery: "80Whr (Up to 4-5 hours typical usage)",
      Weight: "2.01 kg",
      OS: "Windows 11 Home",
    },
    features: [
      "CNC Aluminum body for sleek premium durability",
      "NVIDIA RTX 4070 with Ray Tracing support",
      "240Hz QHD display for crystal-clear smooth motion",
      "Chamber cooling system keeps temperatures low",
    ],
    reviews: [
      "Absolute beast! Rendering 4K videos in Premiere Pro takes minutes. The aluminum chassis feels exactly like a black MacBook.",
      "Thermals are good but fans get loud when playing Cyberpunk in Ultra settings. Battery life is short, only 3.5 hours of productivity.",
      "Extremely expensive, but if you want the best gaming/editing Windows machine, this is it.",
    ],
    image: "laptop_gaming_razer",
  },
  {
    title: "Lenovo IdeaPad Slim 3",
    brand: "Lenovo",
    price: 37990,
    rating: 4.1,
    category: "laptops",
    description: "Affordable thin and light laptop powered by Intel Core i3-1215U, 8GB RAM, and 512GB SSD. Perfect for online classes, spreadsheet work, basic office tasks, and browsing. Extremely budget-friendly and lightweight laptop.",
    specifications: {
      Processor: "Intel Core i3-1215U (6 Cores/8 Threads)",
      RAM: "8GB LPDDR5 RAM",
      Storage: "512GB NVMe SSD",
      Display: "15.6-inch FHD (1920 x 1080) Anti-glare",
      Battery: "47Whr (Up to 5.5 hours battery life)",
      Weight: "1.63 kg",
      OS: "Windows 11 Home",
    },
    features: [
      "Physical privacy shutter on HD webcam",
      "Rapid charge boost (2 hours of use in 15 mins)",
      "Slim bezels with high screen-to-body ratio",
      "Dolby Audio tuned speakers",
    ],
    reviews: [
      "Best budget laptop for office use. Very lightweight and runs MS Office smoothly. Boot time is fast due to SSD.",
      "The screen viewing angles are mediocre, and the build is plastic. But at 38k, you can't complain.",
      "Keyboard is surprisingly tactile. Decent battery for daily browsing. Good for parents or kids.",
    ],
    image: "laptop_lenovo_slim",
  },

  // SMARTPHONES
  {
    title: "iPhone 15 Pro Max",
    brand: "Apple",
    price: 147900,
    rating: 4.9,
    category: "smartphones",
    description: "Forged in titanium, featuring the groundbreaking A17 Pro chip, a customizable Action button, the most powerful iPhone camera system ever with 5x Telephoto optical zoom, and a USB-C port. Exceptional battery life and titanium finish.",
    specifications: {
      Processor: "Apple A17 Pro chip (6-core CPU, 6-core GPU)",
      RAM: "8GB RAM",
      Storage: "256GB SSD storage",
      Display: "6.7-inch Super Retina XDR OLED screen with ProMotion (120Hz)",
      Camera: "48MP Main + 12MP Ultra Wide + 12MP 5x Telephoto",
      Battery: "4441 mAh (Up to 29 hours video playback)",
      Weight: "221 g",
      OS: "iOS 17",
    },
    features: [
      "Aerospace-grade titanium design is light and strong",
      "A17 Pro chip brings console-grade gaming to mobile",
      "5x Telephoto optical zoom camera for close-ups",
      "USB-C connector with USB 3 speeds",
    ],
    reviews: [
      "The switch to Titanium makes a huge difference in weight. The camera zoom is phenomenal, captured crisp moon shots.",
      "Best battery life on an iPhone yet. I easily get 9 hours of screen-on-time. iOS 17 is clean and fluid.",
      "Very expensive, and it doesn't ship with a charging block in the box, which is annoying.",
    ],
    image: "phone_apple_15",
  },
  {
    title: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    price: 129999,
    rating: 4.8,
    category: "smartphones",
    description: "The ultimate Android flagship featuring Galaxy AI, an integrated S Pen stylus, a durable Titanium frame, and Snapdragon 8 Gen 3. Equipped with a 200MP main camera and 100x digital space zoom. Crystal clear QHD+ AMOLED display with anti-reflective glass.",
    specifications: {
      Processor: "Snapdragon 8 Gen 3 for Galaxy",
      RAM: "12GB LPDDR5X RAM",
      Storage: "256GB UFS 4.0 storage",
      Display: "6.8-inch Dynamic AMOLED 2X, QHD+, 120Hz, 2600 nits, Anti-glare",
      Camera: "200MP Main + 50MP Periscope + 12MP Ultra Wide + 10MP Telephoto",
      Battery: "5000 mAh (45W fast charging, wireless charging)",
      Weight: "232 g",
      OS: "Android 14 with One UI 6.1",
    },
    features: [
      "Integrated S-Pen for sketching, writing, and controls",
      "Galaxy AI tools: Live Translate, Circle to Search, Note Assist",
      "Anti-reflective screen provides incredible visibility in sunlight",
      "Massive 200MP sensor for extreme photo detail",
    ],
    reviews: [
      "The anti-reflective glass is magic! No glare even directly under the sun. S-Pen is extremely handy for PDF markups.",
      "Galaxy AI is actually useful, especially the article summaries and image editing. 100x zoom is neat, though noisy.",
      "The phone is quite bulky and wide in the hand. Hard to use one-handed, but performance is unmatched.",
    ],
    image: "phone_samsung_s24",
  },
  {
    title: "OnePlus 12R",
    brand: "OnePlus",
    price: 39999,
    rating: 4.5,
    category: "smartphones",
    description: "Flagship performance at an affordable price. Features Snapdragon 8 Gen 2, 8GB RAM, and a stunning 1.5K LTPO AMOLED screen. Boasts a huge 5500 mAh battery with 100W SUPERVOOC charging that fully charges the phone in 26 minutes.",
    specifications: {
      Processor: "Snapdragon 8 Gen 2",
      RAM: "8GB LPDDR5X RAM",
      Storage: "128GB UFS 3.1 storage",
      Display: "6.78-inch 1.5K AMOLED, 120Hz, HDR10+, 4500 nits peak brightness",
      Camera: "50MP Main (Sony IMX890) + 8MP Ultra Wide + 2MP Macro",
      Battery: "5500 mAh (100W wired fast charger included)",
      Weight: "207 g",
      OS: "Android 14 with OxygenOS",
    },
    features: [
      "Blazing fast 100W charging (Full charge in under 30 mins)",
      "Massive 5500 mAh battery for extreme endurance",
      "Alert Slider for quick profile switching",
      "Vapor chamber cooling for sustained gaming",
    ],
    reviews: [
      "Charging speed is mind-blowing. I plug it in for 10 minutes while getting ready and I'm good for the day. Smooth UI.",
      "The main camera is good in daylight, but the ultra-wide and macro cameras are just average. Display is gorgeous.",
      "Best phone under 40k. Gaming is buttery smooth, no lag in Genshin Impact whatsoever.",
    ],
    image: "phone_oneplus_12r",
  },
  {
    title: "Redmi Note 13 Pro",
    brand: "Xiaomi",
    price: 21999,
    rating: 4.2,
    category: "smartphones",
    description: "Exceptional budget phone featuring a 200MP camera with Optical Image Stabilization (OIS), a 1.5K curved AMOLED screen, and a Snapdragon 7s Gen 2 processor. 67W Turbo Charge gets you to 50% in 15 minutes.",
    specifications: {
      Processor: "Snapdragon 7s Gen 2",
      RAM: "8GB RAM",
      Storage: "128GB storage",
      Display: "6.67-inch 1.5K Curved AMOLED, 120Hz",
      Camera: "200MP Main with OIS + 8MP Ultra Wide + 2MP Macro",
      Battery: "5100 mAh (67W charger in box)",
      Weight: "187 g",
      OS: "Android 13 with MIUI",
    },
    features: [
      "Incredible 200MP camera for ultra-high-resolution detail",
      "Stunning curved display that feels premium in hand",
      "IP54 splash and dust resistance",
      "Headphone jack (3.5mm) included",
    ],
    reviews: [
      "The display is curved and looks very expensive. 200MP photos are sharp, and OIS helps a lot in night shots.",
      "MIUI has some bloatware apps pre-installed. The battery easily lasts a full day, and the 67W charging is fast.",
      "Decent processor for day-to-day apps, but not meant for heavy high-end gaming. Great camera and screen for the price.",
    ],
    image: "phone_redmi_13",
  },

  // HEADPHONES
  {
    title: "Sony WH-1000XM5",
    brand: "Sony",
    price: 29990,
    rating: 4.7,
    category: "headphones",
    description: "Industry-leading wireless active noise-canceling over-ear headphones. Features 8 microphones, Auto NC Optimizer, Speak-to-Chat function, and up to 30 hours of battery life. Ultimate travel and office audio companion.",
    specifications: {
      Type: "Over-Ear Wireless",
      Driver: "30mm Dynamic Driver",
      "Noise Cancelling": "Industry-Leading Active Noise Cancelling (ANC)",
      "Battery Life": "Up to 30 hours (ANC On), Up to 40 hours (ANC Off)",
      Weight: "250 g",
      Connectivity: "Bluetooth 5.2, Multipoint connection (2 devices)",
      "Charging Port": "USB Type-C (Quick charge: 3 mins gives 3 hours playback)",
    },
    features: [
      "Industry-leading noise cancellation adapts to your environment",
      "Speak-to-Chat automatically pauses music when you speak",
      "Crisp hands-free calls with 4 beamforming microphones",
      "Multipoint connection allows pairing two devices simultaneously",
    ],
    reviews: [
      "Noise cancellation is scary good. I can sit in a noisy office or plane and hear absolutely nothing. Comfort is amazing.",
      "Sound is very balanced. Bass is deep but clean. The carry case is a bit bulky compared to the older XM4, but folds flat.",
      "Touch sensors on the earcups are very sensitive, sometimes triggers by mistake. Pricey, but worth every rupee.",
    ],
    image: "audio_sony_xm5",
  },
  {
    title: "Apple AirPods Pro 2",
    brand: "Apple",
    price: 24900,
    rating: 4.8,
    category: "headphones",
    description: "True wireless earbuds featuring the H2 chip, advanced Active Noise Cancellation, Adaptive Audio, and Personalized Spatial Audio. Up to 6 hours of listening time on a single charge and USB-C MagSafe Case with speaker and lanyard loop.",
    specifications: {
      Type: "In-Ear True Wireless (TWS)",
      Processor: "Apple H2 chip",
      "Noise Cancelling": "Active Noise Cancellation & Adaptive Transparency",
      "Battery Life": "Up to 6 hours (24 hours total with charging case)",
      Weight: "5.3 g (per earbud), 50.8 g (case)",
      Connectivity: "Bluetooth 5.3, Apple Ecosystem Auto-switching",
      Charging: "USB-C, MagSafe, Apple Watch Charger compatible",
    },
    features: [
      "H2 chip delivers smarter noise cancellation and 3D sound",
      "Adaptive Audio dynamically blends ANC and Transparency modes",
      "Loud sound tracking case with Find My integration",
      "Touch control allows sliding up or down to adjust volume",
    ],
    reviews: [
      "Adaptive transparency is brilliant. It lets normal conversations in but instantly dampens loud construction drilling sounds.",
      "Fits securely in my ears during jogs. Seamless switching between my iPhone, Mac, and iPad is incredibly smooth.",
      "The battery life is slightly lower than competitor earbuds, but the case features (speaker, MagSafe) make up for it.",
    ],
    image: "audio_apple_airpods",
  },
  {
    title: "boAt Rockerz 450",
    brand: "boAt",
    price: 1499,
    rating: 3.9,
    category: "headphones",
    description: "Highly budget-friendly wireless on-ear headphones with 40mm drivers, punchy bass, up to 15 hours of playback, and integrated controls. Features dual connectivity (Bluetooth + AUX line).",
    specifications: {
      Type: "On-Ear Wireless",
      Driver: "40mm Dynamic Driver",
      "Noise Cancelling": "Passive noise isolation",
      "Battery Life": "Up to 15 hours playback",
      Weight: "168 g",
      Connectivity: "Bluetooth 4.2 & 3.5mm AUX input",
      Charging: "Micro-USB (Takes about 2 hours to full charge)",
    },
    features: [
      "Super Extra Bass technology for bass-heavy audio profiles",
      "Lightweight on-ear design with padded earcups",
      "Dual mode: Listen wirelessly or via AUX audio cable",
      "Highly affordable entry-level wireless headset",
    ],
    reviews: [
      "Awesome bass for this price! Very lightweight and looks clean. Bluetooth connection is stable.",
      "On-ear pressure can make your ears hurt after 2 hours of continuous use. Micro-USB charging is outdated.",
      "If you want cheap wireless headphones for basic music and videos, it's a solid buy. Don't expect ANC or high clarity.",
    ],
    image: "audio_boat_450",
  },

  // TABLETS
  {
    title: "iPad Air 5th Gen",
    brand: "Apple",
    price: 59900,
    rating: 4.7,
    category: "tablets",
    description: "Versatile tablet powered by the desktop-class Apple M1 chip. Features a 10.9-inch Liquid Retina display, 12MP Ultra Wide front camera with Center Stage, and compatibility with Apple Pencil 2 and Magic Keyboard. Perfect for digital art, study notes, and media editing.",
    specifications: {
      Processor: "Apple M1 chip (8-core CPU, 8-core GPU)",
      RAM: "8GB RAM",
      Storage: "64GB storage",
      Display: "10.9-inch IPS Liquid Retina display (2360 x 1640)",
      Camera: "12MP Wide Rear + 12MP Ultra Wide Front with Center Stage",
      Battery: "28.6Whr (Up to 10 hours web surfing or video)",
      Weight: "461 g",
      OS: "iPadOS 17",
    },
    features: [
      "M1 chip delivers massive performance leap over past models",
      "12MP Front Camera with Center Stage keeps you in frame on calls",
      "Supports Apple Pencil 2nd gen with magnetic attachment and charging",
      "Touch ID integrated in the top power button",
    ],
    reviews: [
      "Using this for university notes with Apple Pencil. Writing feels lag-free, and GoodNotes runs like a dream.",
      "Performance is amazing, feels faster than my old laptop. However, the base 64GB storage gets full too quickly.",
      "Screen colors are excellent. M1 chip means it can easily edit multiple tracks of 4K video in LumaFusion.",
    ],
    image: "tablet_apple_air5",
  },
  {
    title: "Samsung Galaxy Tab S9 FE",
    brand: "Samsung",
    price: 34990,
    rating: 4.4,
    category: "tablets",
    description: "Water and dust-resistant Android tablet (IP68) with an in-box S Pen. Features a 10.9-inch 90Hz display, Exynos 1380 processor, and Samsung DeX mode for a PC-like computing experience. Great mid-range productivity tablet.",
    specifications: {
      Processor: "Samsung Exynos 1380",
      RAM: "6GB RAM",
      Storage: "128GB (Expandable up to 1TB via MicroSD)",
      Display: "10.9-inch WUXGA+ LCD screen, 90Hz refresh rate",
      Camera: "8MP Rear + 12MP Ultra Wide Front",
      Battery: "8000 mAh (45W fast charging support)",
      Weight: "523 g",
      OS: "Android 13 with One UI Tab",
    },
    features: [
      "IP68 dust and water resistance (tablet and S-Pen)",
      "S-Pen included inside the box (no extra purchase needed)",
      "Samsung DeX mode provides a windowed desktop environment",
      "Expandable storage via MicroSD card slot",
    ],
    reviews: [
      "The fact that S-Pen is included makes this a huge bargain compared to Apple. 90Hz display is very smooth.",
      "IP68 rating is awesome; I can watch videos in the bath or kitchen without worry. DeX mode is very neat.",
      "The processor is decent, but can stutter slightly under heavy split-screen multitasking. Battery is solid.",
    ],
    image: "tablet_samsung_s9fe",
  },
  {
    title: "Lenovo Tab M10 Gen 3",
    brand: "Lenovo",
    price: 12999,
    rating: 4.0,
    category: "tablets",
    description: "Highly affordable 10.1-inch tablet for family entertainment. Features a Full HD display, Unisoc T610 processor, dual speakers with Dolby Atmos, and Google Kids Space. Ideal for streaming, e-reading, and children's educational use.",
    specifications: {
      Processor: "Unisoc T610 Octa-Core",
      RAM: "3GB RAM",
      Storage: "32GB (Expandable up to 128GB)",
      Display: "10.1-inch IPS LCD, WUXGA (1920 x 1200)",
      Camera: "8MP Rear + 5MP Front",
      Battery: "5100 mAh (Up to 9 hours video streaming)",
      Weight: "460 g",
      OS: "Android 11",
    },
    features: [
      "10.1-inch Full HD display is sharp for streaming Netflix",
      "Dual speakers with Dolby Atmos for immersive sound",
      "TUV Rheinland certified low blue light screen protection",
      "Google Kids Space with preloaded learning content",
    ],
    reviews: [
      "Bought this for my 8-year-old. Perfect for YouTube Kids, zoom classes, and reading. Build is metal and feels sturdy.",
      "Storage is very small (32GB), so you need a microSD card. 3GB RAM is low, apps load slowly.",
      "Excellent screen resolution for this low price. Perfect bed-side Kindle and Netflix screen.",
    ],
    image: "tablet_lenovo_m10",
  },

  // SMARTWATCHES
  {
    title: "Apple Watch Series 9",
    brand: "Apple",
    price: 41900,
    rating: 4.8,
    category: "smartwatches",
    description: "Advanced health tracker featuring the S9 SiP processor, the Double Tap gesture, brighter always-on display, on-device Siri, and precision finding for iPhone. Comprehensive ECG, blood oxygen, and sleep tracking metrics. Apple ecosystem only.",
    specifications: {
      Processor: "Apple S9 SiP",
      Display: "Always-On Retina LTPO OLED, up to 2000 nits brightness",
      "Battery Life": "Up to 18 hours (Up to 36 hours in Low Power Mode)",
      Sensors: "ECG, Blood Oxygen, Temperature sensor, Heart rate, Fall detection",
      Waterproof: "WR50 (Water resistant up to 50 meters, Swimproof)",
      Connectivity: "Wi-Fi, Bluetooth 5.3, GPS",
      OS: "watchOS 10",
    },
    features: [
      "Double Tap gesture lets you control watch hands-free",
      "Brighter Always-on screen (up to 2000 nits, double Series 8)",
      "ECG app capable of generating electrocardiogram wave",
      "Carbon neutral options available in aluminum finishes",
    ],
    reviews: [
      "Double tap gesture is actually useful when my other hand is holding groceries. Brightness in direct sun is great.",
      "Health tracking is extremely accurate. Sleep stages and heart alerts have been spot on. Daily charging is required, though.",
      "Only works with iPhones, which is a bummer. But as an iPhone user, the integration is unmatched.",
    ],
    image: "watch_apple_s9",
  },
  {
    title: "Samsung Galaxy Watch 6",
    brand: "Samsung",
    price: 26900,
    rating: 4.5,
    category: "smartwatches",
    description: "Premium WearOS smartwatch featuring a circular design, slimmer rotating bezel, and advanced sleep coaching, body composition analysis (BIA), ECG, and heart rate monitoring. Integrates seamlessly with Android smartphones.",
    specifications: {
      Processor: "Exynos W930 Dual-Core 1.4GHz",
      Display: "Super AMOLED, Sapphire Crystal glass, Always-on display",
      "Battery Life": "Up to 40 hours (Always-on display Off)",
      Sensors: "BioActive sensor (ECG, HR, BIA), Temperature, Accelerometer",
      Waterproof: "IP68, 5ATM water and dust rating",
      Connectivity: "Wi-Fi, Bluetooth 5.3, NFC, GPS",
      OS: "WearOS 4 powered by Samsung One UI Watch",
    },
    features: [
      "Bioelectrical Impedance Analysis (BIA) calculates body fat & muscle",
      "Detailed Sleep coaching with sleep score and stages breakdown",
      "Scratch-resistant Sapphire Crystal display cover",
      "Thin bezel creates a larger screen layout",
    ],
    reviews: [
      "Body composition metrics match my smart scale closely. Circular screen looks classic. Battery lasts 1.5 days.",
      "The rotating bezel is software-based but mimics the classic physical feel nicely. Great integrations with S24 Ultra.",
      "Some health features like ECG and blood pressure require a Samsung phone, which is unfair to other Android users.",
    ],
    image: "watch_samsung_w6",
  },
  {
    title: "Amazfit GTS 4 Mini",
    brand: "Amazfit",
    price: 7999,
    rating: 4.1,
    category: "smartwatches",
    description: "Ultra-slim and light fitness smartwatch featuring a 1.65-inch HD AMOLED display, 120+ sports modes, 5 satellite positioning systems, and an incredible battery life of up to 15 days on a single charge. Budget-friendly active watch.",
    specifications: {
      Display: "1.65-inch AMOLED, 336 x 384 resolution",
      "Battery Life": "Up to 15 days (Typical usage), 8 days (Heavy usage)",
      Sensors: "BioTracker PPG biometric sensor, SpO2, Heart rate, Accelerometer",
      Waterproof: "5 ATM (Swimproof up to 50 meters)",
      Connectivity: "Bluetooth 5.2, GPS (5 Satellite Positioning)",
      OS: "Zepp OS",
    },
    features: [
      "Ultra-long battery life of 15 days avoids frequent charging",
      "Slim 9.1mm design and super light 19g body",
      "5 satellite GPS systems for accurate outdoor run tracking",
      "24-hour monitoring of heart rate, SpO2, and stress levels",
    ],
    reviews: [
      "Battery is amazing! I charged it once and it lasted 2 weeks with continuous heart tracking. Highly recommended.",
      "AMOLED screen is bright and sharp. The UI is simple, but you cannot reply to WhatsApp messages directly from the watch.",
      "GPS takes about 30 seconds to lock in outdoors, but tracking accuracy is very good for an 8k watch.",
    ],
    image: "watch_amazfit_gts",
  },
];
